### ISSUE TITLE
Installer gives no notification

### ISSUE THREAD

**Issue by 26labs** [electroly/sqlnotebook#15]
Downloaded the msi installer.
When it runs there is no visual feedback.
Suggest to add a "Install Done" message box.

**Comment by electroly** [comment]
I don't think I have control over this unless I switch to an .EXE installer.  I'll look into it.  Do you know of any other applications distributed in an .MSI that offer a notification upon installation completion?

I have considered bundling SQL Notebook as an .appx so that it can go onto the Windows Store, but it's possible it may not satisfy the requirements for Store applications.

**Comment by 26labs** [comment]
I cannot think of any right now.
Perhaps a simple system notification would be ok(to keep current approach), or the EXE can complete wth a messagebox Saying its finished?


Regards,
Matt Taylor

**Comment by Jamleck** [comment]
I had the same issue. Since you are using Wix to create the SQLNotebook.msi installer you should consider using the one of the [Wizards ](https://www.firegiant.com/wix/tutorial/user-interface/ui-wizardry/) that comes with Wix e.g. `<UIRef Id="WixUI_Minimal" />`.

**Comment by electroly** [comment]
Hi Jamleck, thanks for the tip.  Looks pretty straightforward.  I will look into doing that.
