### ISSUE TITLE
Need help exporting to .csv

### ISSUE THREAD

**Issue by fiebinator** [electroly/sqlnotebook#23]
I have a txt file with 9M rows. I want to import it, group by zip code and then export it to csv with the 38K rows that remain. Everything works as desired until I try to export. Two things seem to happen:

1. The first column converts from text to alphanumeric. How do I prevent this?
2. The table seems to truncate at around 10% of the rows, not always in the same spot so I don't think there is something odd in the data.

Thoughts?

Thanks,

Craig

**Comment by electroly** [comment]
Hi Craig.

Do you mean that the leading zeroes on the zip codes are being cut off?  There is a per-column data type option in the import wizard which should preserve those.  If the column is set to text, then the export should be preserving them automatically.  Is it not doing so?

Can you see (with `SELECT COUNT(*) FROM mytable` or similar) whether the full 9M rows are making it into the table?  This will indicate whether it's a problem on import or a problem on export.

**Comment by fiebinator** [comment]
First, thanks for the quick response! Second, here is what I am doing / seeing:


I downloaded the census data into a text file called 'zbp15detail'

Opening the file in Notepad++ shows that all 8.4M rows are present

I imported the file into sql notebook, setting the conversion type and making sure I overwrite any existing tables


[cid:5374b077-0bcf-4aac-9d2a-8bbd7e5e61bd]


I saved that table as USCensusMFG and created a script to only pull the columns I want. It looks like this:


SELECT "zip code","n1_4","n5_9","n10_19","n20_49","n50_99","n100_249","n250_499","n500_999","n1000"

FROM "USCensusMFG"


Counting the zipcodes shows all 8.4M records made it into the table.

[cid:ca57545b-701d-4adf-b16e-9d3610e0143f]


Then I clean things up a little with a script that eliminates two columns and arranges everything around the zip code. I leave the limit command so that I can run tests with a smaller query. I set it to 1,000,000 when I am satisfied.


SELECT "zip code",
    SUM("n1_4"),
    SUM("n5_9"),
    SUM("n10_19"),
    SUM("n20_49"),
    SUM("n50_99"),
    SUM("n100_249"),
    SUM("n250_499"),
    SUM("n500_999"),
    SUM("n1000")
FROM "USCensusMFG"
GROUP BY "zip code"
LIMIT 100000


When this script runs it shows ~39K rows of data, about what you would expect for US zip codes.


[cid:597b1e20-9223-47e1-9058-dbc04fedd9cf]


I click 'Send to' and make this into a table and then I export the table to csv.

When I open the file Excel I now see that I have all 38K rows but Excel indicates an error and has converted the zip code column to numeric. Can you see where I am missing a step?

[cid:23471404-64e5-4b80-8ddd-e92a4fd951c6]


Thanks again,


Craig

________________________________

**Comment by electroly** [comment]
It looks like there might have been some images in your response that didn't make it to GitHub, but I believe I located the same US Census data file and I replicated your steps.  If you open the exported CSV file in Notepad++ you should see that the zip codes are OK and have not been converted to numeric by SQL Notebook.

The culprit is Excel.  If you use File>Open or double-click a CSV file, it will automatically infer the data type of each column, and it decides the zip codes are numeric.  There is an alternate way to import CSV files in Excel that avoids this problem.  Open a blank Excel document and go under the Data tab in the ribbon.  There should be a "From Text" or "From Text/CSV" button, or a "Get Data" button that opens a menu with "From Text/CSV" in it.  You can select your exported CSV file and then it opens a wizard rather than automatically choosing defaults for everything.

There are two different forms of this wizard.  If it looks like the following picture, change the "Data Type Detection" option to "Do not detect data types" and click Load.  The zip codes should import properly.
![image](https://user-images.githubusercontent.com/171909/28899092-34ea23dc-77b7-11e7-9981-353f13459d03.png)

The "legacy" wizard looks like the following animation.  It's a few more clicks to get through this wizard, but the key is on step 3, choosing the "text" data type for the zip code column.  Click the image to see it in full size.
![sqlnotebook](https://user-images.githubusercontent.com/171909/28899119-63a3ec12-77b7-11e7-9fd9-563c5b4c07ac.gif)

I get the full set of rows in Excel with correct zip code formatting using this technique.  Let me know if you have any problems.

**Comment by fiebinator** [comment]
This is insanely helpful. I cannot thank you enough!

Craig

________________________________
