### ISSUE TITLE
Unable to save SQL Notebooks due to "Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by muelphil** [electroly/sqlnotebook#48]
As the title says I'm unable to save Notebooks due to the error "Object reference not set to an instance of an object.". This happens after hitting Save or Save as... and selecting a save location.

![image](https://user-images.githubusercontent.com/31062727/168759250-370686e7-c9ae-4000-89ef-a81595deb6f0.png)

It's rather unfortunate, as I lost all my progress in creation of a notebook. I was able to save Notebooks as long as there were only tables in them I believe, but I am not 100% sure about that.

EDIT: I tried 1.1, 1.2 and 1.2 portable, the error is the same for all of these. I am running a Windows 10 PC.

**Comment by electroly** [comment]
Hi @muelphil, sorry this happened! Can you try it in a new notebook and see what triggers it? If a fresh, new notebook can be saved without error, what needs to happen to break it?

**Comment by muelphil** [comment]
I experimented again. When I save a plain Notebook it works. Also when there are tables and scripts present. As soon as I introduce a page - can be completly empty - it wont save anymore with the given error message.

Hope that helps. Feel free to ask further questions.

I really like this software and would like to use it in school for teaching. With some more features this would be perfect for my usecase. So i hope it gets fixed soon :-)

**Comment by techb0lt** [comment]
I faced the same issue as well. Although if I removed all SQL blocks and saved them as scripts it saved without error. However as soon as I add a sql block it gives the error again.

**Comment by jchalfant** [comment]
Hi All - I appreciate the work that has gone into SQL Notebook. I chose it over Jupyter + an SQL extension because there were so many versions of the latter and they had many disparate dependencies. Conversely, SQL Notebook had what I wanted right out of the box. But... it's crashing and losing my work frequently. I'm simply working in a page and creating interleaving blocks of text and SQL code and if I don't save every 3 minutes I will invariable lose a block or two of work. Very frustrating.

I'm using 1.2.0. The tables I'm using were imported from CSV files and contain hundreds to thousands of records, with not more than a dozen columns. And most of the SQL code is right out of sqlitetutorial.net. In other words, I'm doing what I think is pretty basic stuff, but it's crashing a lot.

Please let me know what other info I can provide to assist resolution. I would really love to be able to use SQL Notebook for me and my team.

Thank you!

**Comment by Sashank-PK** [comment]
I had encountered the same issue, however, I was getting this error after creating a page.  Once I had executed all the cells in the page, I had no errors while saving. 

Not a solution, but an observation I noted.

**Comment by electroly** [comment]
This issue has been fixed in version 1.2.1. Please give it a try.
